### ISSUE TITLE
Use .nodeSize instead of .dx and .dy?

### ISSUE THREAD

**Issue by jstcki** [interactivethings/d3-indent#1]
See mbostock/d3#1211. This would bring the API more in line with existing D3 layouts.

Although the nice thing about the current implementation is that functions can be provided instead of having to use the same size for all nodes.

**Comment by jstcki** [comment]
I tried to bring the API in line with existing tree layouts.

`.nodeSize([x, y])` doesn't take functions as arguments.

To separate some nodes more from others `.separation(function(a, b) { return ...; })` can be used, where `a` is the current node and `b` the previous one (not just the previous sibling, as `node.y` increments across all depth levels).

The separation return value is simply a multiplicator for the y-increment specified by `.nodeSize()`.

**Comment by jstcki** [comment]
Any thoughts @naehrstoff? Do we also need a `.size()` method?

**Comment by grossbart** [comment]
I like the change from `.dx` and `.dy`, it kind of hides the implementation details. And if it's more in line with other layouts, all the better!

I haven't seen a `.nodeSize()` method anywhere else, only the `.size()` one. What would be an example of that?

But really, I'm not that much of a layout expert yet, so you might need to enlighten me a little before I can give competent input on this topic :)

**Comment by jstcki** [comment]
`.nodeSize()` will be introduced in D3 3.2. `.size()` defines the size of the whole layout, and nodes get placed within that, whereas `.nodeSize()` defines the size of each node, making the overall layout size variable. They're mutually exclusive.
