### ISSUE TITLE
How to add expand/collapse function on each level? and add rollup on each level?

### ISSUE THREAD

**Issue by qidonna** [interactivethings/d3-indent#2]

**Comment by jstcki** [comment]
Hi, sorry for the belated reply. If I understand your question correctly, this is something which needs to be solved by changing the data passed in to the layout function. d3-indent only calculates positions based on data, so if you want to collapse a subtree, you could remove it from the data. d3's [nesting functions](https://github.com/d3/d3-collection#nests) can be very useful here.
